#server
server:
  port: 8080
#DB
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: 1234
  #JPA properties
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  #MVC
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp